---
name: addressable
version: '2.8'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 2b3fb8480d3433c9c4b083ad52430a8253efbe5b
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
